language: node_js

sudo: true

dist: trusty

node_js:
  - "10.15.1"

cache:
  npm: true
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

jobs:  
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: npm run test
    - stage: build
      name: "Build project"
      script: npm run build
      
script:
  - npm run test
  # Run and check coverage information
  - codecov
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js